### ISSUE TITLE
28th-oct standup meeting

### ISSUE THREAD

**Issue by kimothokamau** [RailonA/sign-up-simulator-page#1]
- margin-bottom between labels and input
- padding for top-right button
- legal , privacy, security are anchor tags/links

**Comment by kimothokamau** [comment]
- border radius for the form

**Comment by pacyL2K19** [comment]
Hey dear, great job @RailonA @DsunilK 
> Don't forget to add padding to the footer of your form so that I'll look like the sample page

**Comment by SunilDevalla** [comment]
Made all the changes as suggested above, Thank you, team.
